name: Regression
on:
  push:
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Clear Cypress Cache
        run: npx cypress cache clear
      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/Naukri.cy.js
      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: Mochawesome HTML Report
            path: cypress/reports/html

